language: cpp

# build/test on windows
os: windows

script:
    - cmake .
    - cmake --build . --config Release

jobs:
    include:
        # TODO: separate tests according to type
        - stage: test
          name: "Run Unit Tests"
          script: ctest -C Release .
          
stages:
    - compile
    - test
