language: cpp

# build/test on windows
os: windows

cache: ccache;

jobs:
    include:
        - stage: compile
          name: "Compile Source"
          script:
            - cmake .
            - cmake --build . --config Release
            - echo "$TRAVIS_BUILD_ID"
        
        # TODO: we should share artifacts from compile for unit tests
        # TODO: we should split up unit tests according to functionality
        - stage: test
          name: "Run Unit Tests"
          script: 
            - cmake .
            - cmake --build . --config Release
            - ctest -C Release .
          
stages:
    - compile
    - test
